version: "3.7"

services: 
    flask:
        build: ./flask
        container_name: flask
        restart: always
        environment: 
            - APP_NAME=MyFlaskApp
            - DB_USERNAME=dd4f
        expose:
            - "8080"
    
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports:
            - "81:80"
        environment:
            - VIRTUAL_HOST=flaskapp.dd4f.sh,www.flaskapp.dd4f.sh